Update chroot from Debian 12 to 13
Debian 12 is still on glibc 2.36. Still getting:

    /run/firejail/lib/fseccomp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /run/firejail/lib/fseccomp)
    Error: failed to run /run/firejail/lib/fseccomp, exiting...