Update chroot from Debian 11 to 12
Fixes firejail error:

    /run/firejail/lib/fseccomp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /run/firejail/lib/fseccomp)
    /run/firejail/lib/fseccomp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /run/firejail/lib/fseccomp)
    /run/firejail/lib/fseccomp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /run/firejail/lib/fseccomp)
    Error: failed to run /run/firejail/lib/fseccomp, exiting...